[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r annotation_tool/backend/requirements.txt"]

[start]
cmd = "cd annotation_tool/backend && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app"
