[phases.setup]
nixPkgs = ["python311", "libGL", "glib", "libxcb"]
aptPkgs = ["libgl1-mesa-glx", "libglib2.0-0"]

[phases.install]
cmds = ["pip install -r annotation_tool/backend/requirements.txt"]

[start]
cmd = "cd annotation_tool/backend && python app.py"
